### ISSUE TITLE
add zh_tw

### ISSUE THREAD

**Issue by jotarun** [SwitchbladeBot/lorassets#1]
zh_tw data is actually available though not listed on the official site.

**Comment by pedrofracassi** [comment]
That's already available! We currently have every language that the game supports, and are waiting for `pl_pl`, which is coming in 1.2.

You can check which locales are available through the `metadata.json` file: https://lorassets.switchblade.xyz/metadata.json

**Comment by pedrofracassi** [comment]
I've updated the `metadata.json` example to reflect all supported locales.
