### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by Billzabob** [SwitchbladeBot/lorassets#2]
I was thinking about using this since it seems like a really nice idea but it doesn't seem to be up to date with the cards in the latest LoR patch. It says it's automatically built but I don't see how that is happening.

**Comment by pedrofracassi** [comment]
Well it _is_ automatically built, we just have to trigger a build manually. I'll look into running the builds as cronjobs so data stays up to date.

**Comment by pedrofracassi** [comment]
I've manually triggered a build, so it should be serving the latest version now. Currently working on getting daily builds to work.

**Comment by Billzabob** [comment]
Awesome! Thanks Pedro, let me know when you get that working 👍

**Comment by pedrofracassi** [comment]
Just finished refactoring our build code to work with GitHub Actions. Daily builds should work now!
